export const ui = {
  queue: [],
  channels: [],
  categories: [],
  history: [],
  failed: [],
  helperOn: false,
  llmReady: false,
  selected: new Set(),
  historySelected: new Set(),
  filter: { type: "all", value: "" },
  showOlder: false,
  showChannelFilters: false,
  jobs: new Map(),
  openNote: null,
  docMode: "note",
  showTimestamps: true,
  descEdit: true,
  descReedit: false,
  descOpen: true,
  composerTall: false,
  composerDrafts: {},
  composerVideoId: "",
  prefillOpen: false,
  noteJustOpened: false,
  historyFilter: { category: "", source: "", desc: "" },
  branchMode: false,
  branchPrompts: [""],
};
